class Movie {
  static List<Movie> getMovies() => [
        Movie(
          "Iron Man",
          "2008",
          "...",
          "2 May 2008",
          "2H 6Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://www.themoviedb.org/t/p/original/gSDoME541NMgSEXydXgG6BFc47U.jpg",
          "79",
          "7.9/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Home Alone",
          "1990",
          "...",
          "16 Nov 1990",
          "1H 43Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "When bratty 8-year-old Kevin McCallister (Macaulay Culkin) acts out the night before a family trip to Paris, his mother (Catherine O'Hara) makes him sleep in the attic. After the McCallisters mistakenly leave for the airport without Kevin, he awakens to an empty house and assumes his wish to have no family has come true. But his excitement sours when he realizes that two con men (Joe Pesci, Daniel Stern) plan to rob the McCallister residence, and that he alone must protect the family home.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://i.pinimg.com/originals/e0/b0/8a/e0b08aa250191bc37742f9115319a091.jpg",
          "79",
          "7.6/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Avengers",
          "2012",
          "...",
          "11 May 2012",
          "2H 23Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "When Thor's evil brother, Loki (Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury (Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury's dream team are Iron Man (Robert Downey Jr.)",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
          "79",
          "8/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Titanic",
          "1997",
          "...",
          "17 Dec 1997",
          "3H 14Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://c8.alamy.com/comp/T0JG1G/leonardo-dicapriokate-winslet-poster-titanic-1997-T0JG1G.jpg",
          "79",
          "7.8/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Catch Me",
          "2002",
          "...",
          "25 Dec 2002",
          "2H 21Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BZWNjNGRmNGEtYjRjNS00YzEwLWExZmEtMzAzMDhiMjFhZGRiXkEyXkFqcGdeQXVyMjQ0NzE0MQ@@._V1_.jpg",
          "79",
          "8.1/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "EndGame",
          "2019",
          "...",
          "26 April 2019",
          "2H 6Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "A billionaire industrialist and genius inventor, Tony Stark (Robert Downey Jr.), is conducting weapons tests overseas, but terrorists kidnap him to force him to build a devastating weapon. Instead, he builds an armored suit and upends his captors. Returning to America, Stark refines the suit and uses it to combat crime and terrorism",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg",
          "79",
          "8.4/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "I am Legend",
          "2007",
          "...",
          "14 Dec 2007",
          "1H 41Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "Robert Neville (Will Smith), a brilliant scientist, is a survivor of a man-made plague that transforms humans into bloodthirsty mutants. He wanders alone through New York City, calling out for other possible survivors, and works on finding a cure for the plague using his own immune blood.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://images.moviesanywhere.com/56c992f18d66817a14cd68de04a10e57/2838a862-a8a4-4f54-9a22-bc2fba7264a3.jpg",
          "79",
          "7.2/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Encanto",
          "2021",
          "...",
          "24 Nov 2019",
          "1H 39Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "The Madrigals are an extraordinary family who live hidden in the mountains of Colombia in a charmed place called the Encanto. The magic of the Encanto has blessed every child in the family with a unique gift -- every child except Mirabel. However, she soon may be the Madrigals last hope when she discovers that the magic surrounding the Encanto is now in danger.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://www.themoviedb.org/t/p/original/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
          "79",
          "7.3/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Hard Kill",
          "2020",
          "...",
          "21 Aug 2020",
          "1H 38Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "Mercenaries race against the clock to stop a madman from using a computer program to wreak havoc around the globe.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://www.themoviedb.org/t/p/original/jff2Ch6x10kUDj2ipf5DnX3R3pH.jpg",
          "79",
          "3.3/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Eternals",
          "2021",
          "...",
          "5 Nov 2021",
          "2H 37Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://www.themoviedb.org/t/p/original/lYYUrFTl0JtEvqxjQLsodTe4j0S.jpg",
          "79",
          "6.8/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Vikings",
          "2013",
          "...",
          "3 March 2013",
          "5 Seasons",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore - and raid - the distant shores across the ocean. ... The series tells the saga of Ragnar's band of Viking brothers and his family as he rises to become King of the Viking tribes.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BODk4ZjU0NDUtYjdlOS00OTljLTgwZTUtYjkyZjk1NzExZGIzXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
          "79",
          "8.5/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "The Outback",
          "2021",
          "...",
          "2 Dec 2021",
          "1H 32Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "Tired of being locked in a reptile house where humans gawk at them like they're monsters, a group of Australia's deadliest creatures plots a daring escape from thee zoo.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://moviesversa.in/wp-content/uploads/2021/12/Back-to-the-Outback.jpg",
          "79",
          "6.6/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "The Matrix",
          "1999",
          "...",
          "31 March 1999",
          "2H 30Min",
          "Action and Adventure",
          "Jon Favreau",
          "Mark Fergus and Hawk Ostby",
          "Robert Downey Jr and Gwyneth Paltrow",
          "Neo (Keanu Reeves) believes that Morpheus (Laurence Fishburne), an elusive figure considered to be the most dangerous man alive, can answer his question -- What is the Matrix? Neo is contacted by Trinity (Carrie-Anne Moss), a beautiful stranger who leads him into an underworld where he meets Morpheus.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
          "79",
          "8.7/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
        Movie(
          "Maze Runner",
          "2018",
          "...",
          "26 Jan 2018",
          "2H 22Min",
          "Action and Adventure",
          "Wes Ball",
          "James Dashner and T.S. Nowlin",
          "Dylan O'Brien and Kaya Scodelario",
          "Thomas leads some escaped Gladers on their final and most dangerous mission yet. To save their friends, they must break into the legendary Last City, a WCKD-controlled labyrinth that may turn out to be the deadliest maze of all. Anyone who makes it out alive will get answers to the questions that the Gladers have been asking since they arrived in the maze.",
          "English",
          "USA",
          "Nominee of Oscar and Won 9 awards ",
          "https://m.media-amazon.com/images/M/MV5BMTYyNzk3MDc2NF5BMl5BanBnXkFtZTgwMDk3OTM1NDM@._V1_.jpg",
          "79",
          "6.3/10",
          "1000744",
          "0371746",
          "Action",
          "Response Was Excelent",
        ),
      ];

  String title;
  String year;
  String rated;
  String released;
  String runtime;
  String genre;
  String director;
  String writer;
  String actors;
  String plot;
  String Language;
  String country;
  String awards;
  String poster;
  String metascore;
  String imdbRating;
  String imdbVotes;
  String imbdID;
  String type;
  String response;

  Movie(
    this.title,
    this.year,
    this.rated,
    this.released,
    this.runtime,
    this.genre,
    this.director,
    this.writer,
    this.actors,
    this.plot,
    this.Language,
    this.country,
    this.awards,
    this.poster,
    this.metascore,
    this.imdbRating,
    this.imdbVotes,
    this.imbdID,
    this.type,
    this.response,
  );
}
